### ISSUE TITLE
model_predict.py can not finish running facing KNeighborsRegressor is not defined.

### ISSUE THREAD

**Issue by Suraporn** [UBC-MDS/energy_efficiency_analysis#45]
$ python src/model_predict.py --train_file='data/processed/train_df.csv'  --test_file='data/processed/test_df.csv' --out_file=src/training_score.png 
Traceback (most recent call last):
  File "/Users/boy_mbp14p/mds_block3/energy_efficiency_analysis/src/model_predict.py", line 71, in <module>
    main( opt["--train_file"],opt["--test_file"] , opt["--out_file"])
  File "/Users/boy_mbp14p/mds_block3/energy_efficiency_analysis/src/model_predict.py", line 40, in main
    "KNN_reg": KNeighborsRegressor(),
NameError: name 'KNeighborsRegressor' is not defined

Need to add,
from sklearn.neighbors import KNeighborsRegressor

**Comment by MNBhat** [comment]
fixed
